version: "3"
services:
  backend:
    container_name: backend_con
    build: .
    image: backend
    ports: 
      - "5000:5000"
    environment:
      - MYSQL_DATABASE=Mongkolthorn
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=MKtorn044752
    volumes:
      - /home/MKT/product-images:/public/product-images
    networks:
      network:
        ipv4_address: 172.27.0.4

networks:
  default:
    external:
      name: network
